### ISSUE TITLE
제한된 확장자 첨부 금지 되어야 할 것 같은데요.

### ISSUE THREAD

**Issue by wookho** [poesis/xe-autoattach#12]
이걸 버그라고 봐야할지 아니면 옵션으로 봐야할지 모르겠지만 이슈로 등록할게요.
저희 사이트에서 고용량움짤이 문제가 되어 회원 전체가 사용하지 않기로 했습니다.

그런데 문제는 자동첨부애드온에서는 게시판설정에 되어있는 확장자를 참조하여 동작하지 않는 것 같습니다.

그래서 외부이미지를 복붙하는 과정에서 고용량 움짤이 첨부되는 상황이 벌어지는데요.
게시판설정을 참조하거나 애드온에서 확장자 관리가 필요해 보이는데 이거 어떻게 처리가 안될까요?
당분간 업데이트 예정에 없다고 하니 조심스럽네요.

**Comment by kijin** [comment]
외부 이미지는 확장자가 분명하지 않은 경우가 많아서 (주소가 download.php?file_srl=1234&어쩌고... 이렇게 나오면 확장자를 알 수가 없지요) 확장자 기준의 필터링은 곤란합니다.

1.1.1 버전에서 움직이는 GIF 첨부 금지 기능이 추가되었으니 이걸 활용하시면 될 것 같습니다.
