### ISSUE TITLE
혹시 게시물 삭제시 

### ISSUE THREAD

**Issue by socialskyo** [poesis/xe-autoattach#13]
이 애드온에 의해 첨부된 이미지는 같이 삭제가 되지 않는지요?
캐쉬도 삭제해보고 해도 ftp에 그대로 남아 있어서 질문 드려 봅니다.

**Comment by kijin** [comment]
files/attach/images 아래에 저장된 파일은 직접 첨부한 사진과 100% 똑같이 취급됩니다. 글을 삭제할 때 첨부파일이 함께 삭제되지 않는다면 다른 문제가 있는 거겠지요.

다른 애드온에 의해 첨부된 파일은 삭제되지 않을 수도 있습니다.

**Comment by socialskyo** [comment]
아 그렇군요. 분명히 files/attach/images/숫자~ 여기 경로에 있긴한데... 좀더 확인을 해보겠습니다.
