### ISSUE TITLE
게시물 자동 저장시

### ISSUE THREAD

**Issue by socialskyo** [poesis/xe-autoattach#14]
생각해보면 엄청 까다로울것 같은데 혹시내 해서 올려 봅니다. 제안까지는 아닙니다만...
이미지 자동 저장을 하면 기 걸려있던 a href=src 내의 경로가 

이 애드온에 의해 첨부된 라이믹스 파일 경로로  같이 변경 될순 없을까요?

**Comment by kijin** [comment]
img src만 변환합니다만... a href까지 마구 변환한다면 글쓴이의 의도와 다르게 될 수 있어서요...

**Comment by socialskyo** [comment]
기진곰님이 그렇다면 그런거라 생각하고 우선 close 하겠습니다. ^^
