### ISSUE TITLE
외부이미지 첨부가 안되는 이유가 뭘까요?

### ISSUE THREAD

**Issue by wookho** [poesis/xe-autoattach#16]
```
<div class="rs-card">
<div class="rs-card-img pull-left"><img alt="2017-12-08 14;39;53.jpg" class="view_image" data-autoattach="download-failure" height="361" src="http://www.koreadognews.co.kr/data/tmp/1712/524a2c2e467790b3f2c2d7992271b7fa_bH4ykAtsrIJiKOm2X5GB6e.jpg" width="302" /></div>

<div class="rs-card-txt pull-left">
<div class="rs-card-title p10">소외된 가치에 손 내미는 작가 이순자</div>

<div class="rs-card-content p10">
<p>&nbsp; 인간들에 의해 피해를 입고 처참하게 살아가는 고양이에 안타까움을 느낀 이순자 작가는 오늘도 행복을 그리워하는&nbsp;그녀만의 고양이들을 화폭에 담는다.&nbsp; &#39;길고양이가 제 작품에서만이라도 눈엣가시가 아닌 사랑스...</p>
</div>
</div>
</div>
```
위와 같이 코드가 작성되어 있습니다.

**Comment by wookho** [comment]
XE 1.9.2 업데이트가 되면서 문제가 생기는게 아닐까요? 저희는 php 5.59 입니다.

**Comment by wookho** [comment]
코어에서 문제가 발생한거 같습니다. 다른 모듈에서도 rss로 수집한 이미지를 저희 서버에 업로드해야 하는데 되지 않네요. 그리고 이 애드온도 테스트 해보니 사이트와 상관없이 모두 다  download fail 이 발생하네요.

**Comment by kijin** [comment]
라이믹스 1.9.2 패치하느라 바빠서 아직 여기까지는 살펴보지 못하고 있습니다. 죄송합니다.

이 애드온뿐 아니라 서버에서 외부 데이터를 받아와야 하는 모든 부분에 문제가 있다면 코어의`FileHandler::getRemoteResource()` 함수에 문제가 생긴 것 같네요.

**Comment by kijin** [comment]
`FileHandler::getRemoteFile()`에서 `true`를 반환하는데 실제로 다운로드된 파일은 0바이트로군요.

**Comment by kijin** [comment]
XE 코어 문제입니다. 이미지 자동첨부 애드온에서 따로 패치할 수도 있겠지만 다른 자료도 영향을 받는다면 코어에서 패치해 줘야 할 것 같습니다.

https://xetown.com/qna/820244#comment_821189

**Comment by kijin** [comment]
Fixed in 1.1.4
