### ISSUE TITLE
예외도메인에 애드온사용 도메인도 추가해야 하나요?

### ISSUE THREAD

**Issue by wookho** [poesis/xe-autoattach#2]
이미 본 사이트에서 게시된 이미지의 경우 재활용 목적으로 첨부를 하지않고 이미지를 불려오는 경우가 종종 있는데요.

이런 경우 첨부를 하지 않게 하려면 자신의 사이트 도메인도 입력을 해야 하는지 궁금합니다.

그리고 도메인입력 형식이 도메인.com 이런 형식인지 궁금하네요.

**Comment by kijin** [comment]
현재 페이지가 포함된 도메인과 XE의 기본 URL은 자동으로 예외 처리됩니다.

`domain.com`과 `www.domain.com`은 별도로 취급합니다.

여러 서브도메인을 예외로 지정하려면 `*.domain.com`도 가능합니다.

**Comment by wookho** [comment]
@kijin 그렇군요. 감사합니다~~~

**Comment by kijin** [comment]
현재 사이트는 항상 예외로 한다는 안내문을 설정 페이지에 추가했습니다.
