### ISSUE TITLE
문서첨부제한 무시문제

### ISSUE THREAD

**Issue by d2d2** [poesis/xe-autoattach#3]
문서첨부제한 설정을 무시합니다.
*문서첨부제한은 10mb으로 제한해 놓았지만

외부에서 고화질 이미지링크를 가져오면 문서첨부제한없이 무제한으로  업로드됩니다.

즉, 이미지링크를  100mb 용량만큼 링크시키면 그대로 첨부파일됩니다.
용량이적은 웹호스팅 상품 사용자에게는 치명적일 수 있다고 생각됩니다.

**Comment by kijin** [comment]
용량이 적은 웹호스팅에서 자동 첨부 기능을 사용하는 것 자체가 그다지 안전하지는 않다고 보입니다만...

그러나 큰 서버에서도 수백메가짜리 이미지를 마구 첨부할 경우 문제가 생기는 것은 마찬가지이므로, 각 모듈의 첨부용량 제한을 적용하도록 하는 옵션을 추가했습니다. (단, 최고관리자가 글을 쓰거나 수정할 때는 예외입니다.)
