### ISSUE TITLE
뭐가 문제인지 모르겠어서....

### ISSUE THREAD

**Issue by Syangki** [poesis/xe-autoattach#4]
기존에 외부이미지 저장애드온을 사용하였습니다.(미완성 미작동부분이 좀있죠..)
오늘 자료실에 본애드온이 올라와서 너무좋아서 설칠햇습니다만.
어느건 작동이되고 어느건 작동이 안되네요
http://www.tugijang.com/dogdrip/15685 여기보시면 위에 몇개의 이미지는 첨부되지않았고, 아래의 몇개의 이미지는 첨부가되었습니다..(두번 테스트를 해봤고, 두번다 똑같은 이미지가 첨부되지않았습니다.)

http://www.tugijang.com/dogdrip/15690 이곳도 마찬가집니다.

**Comment by kijin** [comment]
겉으로 봐서는 원인을 알 수 없습니다.

혹시 이미지 순서를 바꾸어도 항상 같은 이미지가 첨부되지 않나요, 아니면 순서와 관계없이 처음 몇 개는 항상 건너뛰나요?

**Comment by kijin** [comment]
변경된 autoattach.class.php 파일로 테스트 부탁드립니다.

**Comment by Syangki** [comment]
잘됩니다. 똑같은 파일일이 이중으로 쓰일경우 하나만 저장하는것 맞죠?
예를들면
<img src="http://test.com/1.jpg><br>
<img src="http://test.com/1.jpg>
이런식으로 되어있을때 두번쨰줄의 이미지가 첨부가되면서 저장이되네요
의도하신것이 맞다면 이슈 클로즈 하셔도 될듯합니다

**Comment by Syangki** [comment]
아참 그리고 2초라는시간이 좀 짧아서 안퍼와질경우가 있던데
`protected static $image_timeout = 2;`
이부분을 늘리면 되는건가요

**Comment by kijin** [comment]
네, 그거 바꾸시면 되지만 아예 애드온 설정 페이지에서 변경 가능하도록 해드릴 예정입니다.
