### ISSUE TITLE
에디터 이미지 삽입이외의 이미지 비작동

### ISSUE THREAD

**Issue by onepang** [poesis/xe-autoattach#5]
http://image.pullbbang.com/image1004/20056148227.jpg

같은 이미지라도 

`<img editor_component="image_link" height="480" src="http://image.pullbbang.com/image1004/20056148227.jpg" style="width: 480px; height: 480px;" width="480" />`

이렇게 에디터에서 이미지 삽입으로 링크로넣으면 잘 변환이 되는데

```
<img src="http://image.pullbbang.com/image1004/20056148227.jpg">
<img src=http://image.pullbbang.com/image1004/20056148227.jpg>
<img src='http://image.pullbbang.com/image1004/20056148227.jpg'>
```

이런 손으로 적은 간단한 소스는 작동이 되지 않습니다.

**Comment by kijin** [comment]
진짜로 이미지가 나와버려서 구분이 되지 않습니다.

깃허브에 소스코드를 붙여넣으시려면 앞에 네 칸 띄워 주세요.

**Comment by onepang** [comment]
http://image.pullbbang.com/image1004/20056148227.jpg

같은 이미지라도 

 

<img editor_component="image_link" height="480" src="http://image.pullbbang.com/image1004/20056148227.jpg" style="width: 480px; height: 480px;" width="480" />

이렇게 에디터에서 이미지 삽입으로 링크로넣으면 잘 변환이 되는데

 

<img src="http://image.pullbbang.com/image1004/20056148227.jpg">

**Comment by onepang** [comment]
앗 그러네요 수정하였습니다.~

**Comment by kijin** [comment]
변경된 autoattach.class.php 파일로 테스트 부탁드립니다.

**Comment by onepang** [comment]
@kijin 완전 잘작동하기 시작했습니다.

감사합니다. ^^

**Comment by onepang** [comment]
`<p><img src="http://image.pullbbang.com/image1004/20056148227.jpg" /></p>`

혹시 이렇게 뒤쪽에 /> 가 붙은이미지도 작동하게 수정이 가능할런지요?

**Comment by kijin** [comment]
그것도 이미 될 텐데요?

**Comment by onepang** [comment]
이상하네요.. 되다가 말다가 ㅠ 원인을 모르겠네요
딱 방금 올려주신 다시 올렸을땐 잘작동하더니 또 작동이 안되네요.

**Comment by onepang** [comment]
@kijin 아아 잘작동 됩니다 감사합니다.
방금은 애드온 수정에서 ㅎㅎ 실수로 하나만 체크가 되었었네요
