### ISSUE TITLE
엑박 아래에 위치한 이미지는 변환이 되지 않습니다.

### ISSUE THREAD

**Issue by onepang** [poesis/xe-autoattach#6]
`<img src="http://asdfasdfsadfsafdfsdsfd.com/xbox.jpg">`
`<img src="http://image.pullbbang.com/image1004/20056148227.jpg">`
이렇게 엑스 박스 뜨는 이미지가 컨텐츠 위쪽에 있고 그아래에
정상적인 이미지 코드가 이렇게 두줄로 들어가있다면

아래에 정상적인 이미지도 변환이 되지 않습니다.

반대로 정상이미지가 위에 있고 아래에 엑박 이미지가 있으면 정상적으로 위에 있는 이미지가 변환됩니다.

**Comment by kijin** [comment]
재현이 되지 않습니다. 제 사이트에서는 엑박이 위에 있어도 아래의 이미지가 정상 첨부됩니다.

**Comment by onepang** [comment]
매번감사드립니다.
아 그문제가 아니네요

`<img src=http://image.pullbbang.com/image1004/20056148227.jpg>`

src에 " 나 ' 가 없는 이미지 태그 일시 작동이 되지 않네요.

어제 메일 주셨던 것 처럼

**Comment by kijin** [comment]
조금 전 수정된 autoattach.class.php로 다시 테스트해 보세요.

**Comment by onepang** [comment]
@kijin 잘 해결되었습니다!
감사드립니다. ^^
