### ISSUE TITLE
1.1 업데이트 후 댓글 등록시 새로고침이 안됩니다.

### ISSUE THREAD

**Issue by wookho** [poesis/xe-autoattach#7]
환경은 PC 스케치북5 입니다. 코어는 최신코어이구요,.
댓글 등록시 새로고침이 되지 않아 댓글입력 상태그대로 유지 됩니다.

강제로 새로고침 후 댓글 등록은 되어 있는 것이 확인되구요.
스케치북5 댓글 입력기능인 이전에 입력하고 등록하지 않은 댓글 정보가 그대로 남아있습니다.

**Comment by kijin** [comment]
Fixed in 41b0a05
