### ISSUE TITLE
이미지 자동 첨부 애드온으로 게시판에 글을 올릴때 &#39;가 간헐적으로 포함되어 등록됩니다.

### ISSUE THREAD

**Issue by solsol0609** [poesis/xe-autoattach#8]
안녕하세요. 이미지 자동 첨부 애드온을 사용 중 입니다. php 버전 5.4, xe 버전 1.8.18입니다.
이미지 자동 첨부 애드온으로 게시판에 글을 올릴때 &#39;가 간헐적으로 포함되어 등록됩니다.
애드온을 끄면 &#39;가 포함되지 않습니다. 이미지 자동 첨부 애드온의 버그 같습니다. 버그 패치 부탁드립니다.

**Comment by kijin** [comment]
어디에 어떻게 포함되어 등록되는지 자세히 알려주세요.

**Comment by solsol0609** [comment]
![10](https://cloud.githubusercontent.com/assets/12867623/13721341/45a80ee0-e867-11e5-83c3-d7f3097ac94f.png)
사진과 같이 단어 앞에 포함되기도 하고 단어 사이에 포함되기도 합니다.

**Comment by kijin** [comment]
제 사이트에서는 증상이 확인되지 않습니다.

에디터 소스에서는 원래 `'`(작은따옴표)가 `&#39;`로 표시되는 것이 정상이지만, 글 내용을 화면에 표시할 때는 작은따옴표 그대로 나옵니다. 사진을 추가하더라도 차이가 없습니다.

사용하시는 다른 애드온과의 상호작용일 수도 있습니다. `#39;`에 링크가 적용되는 것을 보면 혹시 해쉬태그나 자동 링크 관련 기능을 사용하고 계신가요?

**Comment by solsol0609** [comment]
네. 해시태그 애드온 때문이네요.^^ 혹시 해시태그 애드온과 동시에 사용해도 뜨지 않도록 하는 방법이 있을까요?

**Comment by kijin** [comment]
`&#39;`는 이미지 자동첨부 애드온에서 넣은 것이 아니라 XE 자체에서 넣은 것이기 때문에 XE와 해시태그 애드온 사이에서 해결해야 하는 문제입니다.

**Comment by solsol0609** [comment]
네.. 바쁘신 가운데 수고 많으셨습니다. 별거 아닌 거 가지고 이렇게 힘들게 해서 죄송합니다.
